control_nodes:
- {row: 1, col: 1, x: 0.794, y: -0.295, z: 0.557, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 2, x: 0.796, y: -0.298, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 3, x: 0.801, y: -0.301, z: 0.563, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 4, x: 0.804, y: -0.303, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 5, x: 0.808, y: -0.306, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 6, x: 0.81, y: -0.309, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 7, x: 0.813, y: -0.311, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 8, x: 0.817, y: -0.316, z: 0.564, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 9, x: 0.82, y: -0.318, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 1, col: 10, x: 0.823, y: -0.321, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 1, x: 0.792, y: -0.298, z: 0.563, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 2, x: 0.795, y: -0.301, z: 0.563, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 3, x: 0.798, y: -0.304, z: 0.563, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 4, x: 0.801, y: -0.308, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 5, x: 0.805, y: -0.31, z: 0.563, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 6, x: 0.807, y: -0.312, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 7, x: 0.811, y: -0.315, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 8, x: 0.813, y: -0.318, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 9, x: 0.816, y: -0.321, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
- {row: 2, col: 10, x: 0.82, y: -0.325, z: 0.562, qx: 0.998, qy: 0.066, qz: -0.01,
  qw: -0.009}
control_cols: [1, 4, 8, 12, 16]
grid: {rows: 2, cols: 10}
