control_nodes:
- {row: 1, col: 1, x: 0.792, y: -0.13, z: 0.543, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 1, col: 4, x: 0.799, y: -0.125, z: 0.549, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 1, col: 8, x: 0.807, y: -0.117, z: 0.549, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 1, col: 12, x: 0.815, y: -0.108, z: 0.547, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 1, col: 16, x: 0.823, y: -0.101, z: 0.547, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 2, col: 1, x: 0.795, y: -0.133, z: 0.549, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 2, col: 4, x: 0.801, y: -0.128, z: 0.548, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 2, col: 8, x: 0.81, y: -0.119, z: 0.548, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 2, col: 12, x: 0.818, y: -0.111, z: 0.548, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 2, col: 16, x: 0.825, y: -0.104, z: 0.548, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 3, col: 1, x: 0.798, y: -0.135, z: 0.549, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 3, col: 4, x: 0.804, y: -0.129, z: 0.547, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 3, col: 8, x: 0.813, y: -0.121, z: 0.548, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 3, col: 12, x: 0.82, y: -0.113, z: 0.548, qx: 0.713, qy: -0.701, qz: 0.02,
  qw: 0.003}
- {row: 3, col: 16, x: 0.828, y: -0.105, z: 0.548, qx: 0.713, qy: -0.7, qz: 0.02,
  qw: 0.003}
control_cols: [1, 4, 8, 12, 16]
grid: {rows: 3, cols: 16}
